### PR TITLE
fix: fetch results cached st not getting latest data

### LINKED ISSUE #213: Fix(frontend): approve application takes time
**Description**
After clicking approve, directly redirect back to the project page, but still see it's pending on approve, should either prevent user leave the approve process or show `loading...` instead of the pending on approve.

**Related Issues**
#93

### PR DESCRIPTION
**Pull request by kittybest**
**Description**
The attestations are cached for long time, which causes user not getting the latest approved attestations.

**Related Issues**
close #213

### CODE REVIEW

File: src/features/applications/components/AdminButtonsBar.tsx [hunk 1]
```diff
@@ -14,7 +15,11 @@ export const AdminButtonsBar = ({ projectId }: IAdminButtonsBarProps): JSX.Eleme
   const isAdmin = useIsAdmin();
   const { isCorrectNetwork, correctNetwork } = useIsCorrectNetwork();
 
-  const approve = useApproveApplication({});
+  const approve = useApproveApplication({
+    onSuccess: () => {
+      window.location.reload();
```
Comment (0xmad) [inline src/features/applications/components/AdminButtonsBar.tsx:20]: It's not a good practice to reload page on action/success/error.

**Review by 0xmad — CHANGES_REQUESTED** [review]
@kittybest thanks, just one comment

File: src/features/applications/components/AdminButtonsBar.tsx (hunk 1 above)
Comment (kittybest) [reply src/features/applications/components/AdminButtonsBar.tsx]: Agree, but I don't have better way to call fetch immediately 🤔
How about I made the `refetchInterval` to 10 seconds like now?

Comment (0xmad) [reply src/features/applications/components/AdminButtonsBar.tsx]: This lib has something for immediate refetching values, the docs should have this.

Comment (kittybest) [reply src/features/applications/components/AdminButtonsBar.tsx]: So what I wanna do is to refetch instantly in `onSuccess`

Comment (0xmad) [reply src/features/applications/components/AdminButtonsBar.tsx]: Right, but make sure you don't call it in a loop, so if there are no new data, just skip refetching.

Comment (kittybest) [reply src/features/applications/components/AdminButtonsBar.tsx]: I tried several ways, no best way to solve this problem without reloading page now, would think over it tomorrow.

Comment (kittybest) [reply src/features/applications/components/AdminButtonsBar.tsx]: I tried on calling only the `refetch` instead of setting the `refetchInterval`, but it's not working, so I keep this version until the best solution is found.

Comment (kittybest) [reply src/features/applications/components/AdminButtonsBar.tsx]: changed from `onSuccess` to check `approve.isSuccess` and call `refetch` in `useEffect` hook, however still not working QQ

**Comment by kittybest** [comment]
**Problem**
Currently already tried several ways to refetch the latest data, now already made sure it would call `refetch` right after succeeds, but no latest data loaded. Right now I think reload the current page is the best way to complete this PR, we could find another way to solve this problem in the future, but I think it's important to make sure user get the instant update on data status and prevent them from approving same applications.

File: src/features/applications/components/AdminButtonsBar.tsx (hunk 1 above)
Comment (0xmad) [reply src/features/applications/components/AdminButtonsBar.tsx]: Let's create issue for this and todo with a link for this issue.
The solution here is to merge cached values with new data, but I haven't worked with trpc stack closely so I don't know how to merge the data.
If this task is not urgent, you can try to research this one.

Comment (kittybest) [reply src/features/applications/components/AdminButtonsBar.tsx]: Of course the ultimate solution here is to merge the cached data and new data, and the question remains here is "how to get the new data", this worth a new issue.

But I think this PR solves an important problem that should be solved in v1.
So I'm thinking about could we have a temporary solution here for smooth user experience, and delve into the best solution afterwards?  what should the temporary solution be like is my concern QQ

Comment (kittybest) [reply src/features/applications/components/AdminButtonsBar.tsx]: @0xmad how do you think I changed to something like this now? (but I think the data is not updated right after `isSuccess` so should call after something like 3 seconds? the `isSuccess` is too fast which is earlier than the transaction succeeded QQ)

Comment (0xmad) [reply src/features/applications/components/AdminButtonsBar.tsx]: > @0xmad how do you think I changed to something like this now?
Can you show what you mean?

Comment (kittybest) [reply src/features/applications/components/AdminButtonsBar.tsx]: so now I split some functions out the `fetchAttestation.ts` file, and instead of setting `cacheInterval` to 0 for uncached fetch, made another file for normal fetch, since the `node-fetch-cache` package cannot be imported or called in the browser. Once the application is approved, the `useEffect` hook would call normal fetch and merge the results with the original fetch result. 

But if it refetch once it's `isSuccess`, the attestation is actually not yet updated, so I made it sleep for 5 seconds and refetch.

File: src/features/applications/components/ApplicationsToApprove.tsx [hunk 2]
```diff
@@ -146,18 +150,31 @@ type TApplicationsToApprove = z.infer<typeof ApplicationsToApproveSchema>;
...
+  useEffect(() => {
+    const fetchData = async () => {
+      const ret = await fetchApprovedApplications();
+      setRefetchedData(ret);
+    };
+
+    /// delay refetch data for 5 seconds
+    setTimeout(() => {
+      fetchData();
+    }, 5000);
```
Comment (0xmad) [inline src/features/applications/components/ApplicationsToApprove.tsx:176]: let's clear timeout at the end

File: src/features/applications/components/ReviewBar.tsx [hunk 3]
```diff
@@ -1,22 +1,51 @@
...
+  useEffect(() => {
+    const fetchData = async () => {
+      const ret = await fetchApprovedApplications([projectId]);
+      setRefetchedData(ret);
+    };
+
+    /// delay refetch data for 5 seconds
+    setTimeout(() => {
+      fetchData();
+    }, 5000);
```
Comment (0xmad) [inline src/features/applications/components/ReviewBar.tsx:47]: The same here with clearTimeout

File: src/features/applications/components/AdminButtonsBar.tsx (hunk 1 above)
Comment (0xmad) [reply src/features/applications/components/AdminButtonsBar.tsx]: I think it's good as a temporary solution.

File: src/features/applications/components/ApplicationsToApprove.tsx [hunk 4]
```diff
@@ -146,18 +150,32 @@ type TApplicationsToApprove = z.infer<typeof ApplicationsToApproveSchema>;
...
+    const fetchData = async () => {
+      const ret = await fetchApprovedApplications();
+      setRefetchedData(ret);
+    };
+
+    /// delay refetch data for 5 seconds
+    const timeout = setTimeout(() => {
+      fetchData();
+      clearTimeout(timeout);
+    }, 5000);
```
Comment (0xmad) [inline src/features/applications/components/ApplicationsToApprove.tsx:177]:
```suggestion
    const timeout = setTimeout(() => {
      fetchData();
    }, 5000);
    
    return () => clearTimeout(timeout);
```

File: src/features/applications/components/AdminButtonsBar.tsx (hunk 1 above)
Comment (kittybest) [reply src/features/applications/components/AdminButtonsBar.tsx]: open an issue for it: https://github.com/privacy-scaling-explorations/maci-rpgf/issues/229

File: src/features/applications/components/ApplicationsToApprove.tsx (hunk 4 above)
Comment (kittybest) [reply src/features/applications/components/ApplicationsToApprove.tsx:177]: I also wanna do this, but the linter kept on complaining 🤔

**Review by 0xmad — APPROVED** [review]
@kittybest thanks!
